[package]
name = "moddecomp"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
env_logger = "0.11.3"
rand = "0.9.0-alpha.1"
regex = "1.10.5"
criterion = "0.5.1"

[[bench]]
name = "my_benchmark"
harness = false

